os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.3beta
script:
  - swift test -c release -Xswiftc -enable-testing
notifications:
  email:
    on_success: never
    on_failure: change
